apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "proyecto-test-1"
  description: "este es un proyecto con arqui mvc"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: "group:default/admins"
  system: "system:default/system1"
  lifecycle: experimental