site_name: proyecto-test-1
site_description: este es un proyecto con arqui mvc

nav:
  - Home: index.md
  - Parameters: parametros.md
  - Endpoints and methods: endpoints.md
  - Errors: errors.md

plugins:
  - techdocs-core